version: "3.9"

services:
  app:
    build: .
    ports:
      - "5000:5000"
    links:
      - monguito

  monguito:
    image: mongo:latest
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=julis
      - MONGO_INITDB_ROOT_PASSWORD=password
      
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
